### ISSUE TITLE
inputNumber 과제 코드리뷰

### ISSUE THREAD

**Issue by devhaeyeon** [lhyekwang/source#1]
짝짝짝 ! 하시느라 고생 많으셨어요 ~
코드의 정돈도 어느 정도 되어 있는거 같아보여요 ~ 

인상이 깊었던 것은 커스텀 엘리먼트에 타입을 넣어서 
해당 타입에 따라 분기를 치는 부분이었어요 ~ 

## 조건문
조건문에는 세가지 방법이 있어요 ~

- if, else if, else 형태 (if 블라블라로 시작되는)

- 삼항연산자
형태 > 
조건문 ? 참이면 해당 부분 실행 : 거짓이면 해당 부분 실행

- switch
switch (조건을 따질 값) {

case 조건 : 
조건에 충족하면 실행할 부분
break;

default : 
해당 케이스들이 아닌 경우 기본적으로 실행할 부분
break;

여기서 break; 는 꼭 기입!!

[자세한 설명 MDN](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/switch)

## 조건문에서 ===와 == 차이
- 자바스크립트의 경우 타입에 느슨하기 때문에 타입까지 체크를 해주는 ===, !== 으로 해주는 것이 좋답니다.

## 할당연산자 
[관련 내용 링크](https://www.ibm.com/support/knowledgecenter/ko/SSVRGU_9.0.1/reference/r_wpdr_elements_operators_assignment_r.html#r_wpdr_elements_operators_assignment_r)

## parseFloat, parseInt 의 차이 
수학에서 수의 체계는 실수, 정수들이 있습니다. 
실수가 parseFloat, 정수가 parseInt

여기서 이 둘의 공통점은 수가 아닌 문자로 시작하면 NaN을 반환합니다.
https://www.codingfactory.net/11026

## isNaN
[자세한 설명 MDN](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/isNaN)

--
해당 이론들을 적용하여 좀 더 보완해보면

## 조건문에서 ===와 ==의 차이
https://github.com/lhyekwang/source/blob/6df15ac99a62370d26e044113c6fe8abb4952485/study/01_button.html#L29

이 코드를 
```javascript
if(calc === 'minus'){   
```
이런 식으로 수정할 수 있습니다. 

## 조건문 - 삼항연산자

https://github.com/lhyekwang/source/blob/6df15ac99a62370d26e044113c6fe8abb4952485/study/01_button.html#L29-L35

이 코드를 
```javascript
calc === ‘minus’ ? result—; : result++;
```

## 조건문 - switch
https://github.com/lhyekwang/source/blob/6df15ac99a62370d26e044113c6fe8abb4952485/study/01_button.html#L29-L35
이 코드를
```javascript
switch (calc)  {

case 'minus' :
	result—;
	break;
case 'plus' :
	result++;
	break;
}
```
또는 
https://github.com/lhyekwang/source/blob/6df15ac99a62370d26e044113c6fe8abb4952485/study/01_button.html#L24-L38
부분을 
```javascript
switch (calc)  {

case 'minus' :
	num.value -= result;
	break;
case 'plus' :
	num.value += result;
	break;
}
case 'multiply' :
	num.value *= result;
	break;
}
```
이렇게 코드를 짤 수 있습니다 .
여기서 num.value *= result;
이 부분이 할당 연산자라고 합니다.

## parseFloat, parseInt
문자열을 수의 형태로 바꿔주는 함수입니다. 여기서는 0,1,2 는 정수에 가까우니 parseInt가 좀 더 적합할 것 같습니다 .

변경해도 해당 코드에서는 0,1,2 를 입력할 때는 괜찮지만 f,l 과 같은 숫자가 아닌 문자열 등을 입력할 때 
콘솔 창에서 parseFloat('dk')를 입력해보면 NaN이 출력 될 것입니다. 아마 input에 NaN이 출력될 것 같아요.

이를 해결하기 위해서 코드를
https://github.com/lhyekwang/source/blob/6df15ac99a62370d26e044113c6fe8abb4952485/study/01_button.html#L21-L40

```javascript
    function count(){        
        result = num.value; 
        if(typeof result !== 'number') return false; // 요기요기
        result = parseInt(num.value); // 요기요기
        calc = this.getAttribute('data-cl');
           // 요기요기 있던 조건문들은 정리가 됨
            if(calc == 'minus'){             
                //console.log("뺄꺼야");
                result--;
            }else if(calc == 'plus'){
                //console.log("더할꺼야");
                result++;
            } 
        num.value = result;
    }
```

**Comment by lhyekwang** [comment]
https://github.com/lhyekwang/source/blob/1e726463d51d0efac68be809889945433c6c2e63/03_fold.html#L73-L88

**Comment by lhyekwang** [comment]
@devhaeyeon 
비교연산자 타입까지 적용

https://github.com/lhyekwang/source/blob/8020a0c3b16d4d8be57b163bc9df6669faeb0ece/study/01_button.html#L34-L39

스위치문으로 수정
https://github.com/lhyekwang/source/blob/8020a0c3b16d4d8be57b163bc9df6669faeb0ece/study/01_button.html#L40-L47

parseInt 로 변경
https://github.com/lhyekwang/source/blob/8020a0c3b16d4d8be57b163bc9df6669faeb0ece/study/01_button.html#L32

IsNaN 정리
https://bean-1.gitbook.io/workspace/summary/isnan
